package AmfTest::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'AmfTest::Web::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=test',
        user => 'postgres',
        password => '',
    }
);

=head1 NAME

AmfTest::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<AmfTest::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<AmfTest::Web::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.25

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
